In [1]:
%pip install pandas

Collecting pandas
  Downloading pandas-2.2.1-cp311-cp311-win_amd64.whl (11.6 MB)
                                              0.0/11.6 MB ? eta -:--:--
                                              0.2/11.6 MB 3.9 MB/s eta 0:00:03
     --                                       0.8/11.6 MB 8.2 MB/s eta 0:00:02
     ----                                     1.4/11.6 MB 10.1 MB/s eta 0:00:02
     -------                                  2.3/11.6 MB 12.0 MB/s eta 0:00:01
     -----------                              3.3/11.6 MB 14.3 MB/s eta 0:00:01
     ------------                             3.6/11.6 MB 15.2 MB/s eta 0:00:01
     ------------                             3.6/11.6 MB 15.2 MB/s eta 0:00:01
     ------------                             3.6/11.6 MB 15.2 MB/s eta 0:00:01
     ------------                             3.6/11.6 MB 15.2 MB/s eta 0:00:01
     ------------                             3.6/11.6 MB 15.2 MB/s eta 0:00:01
     ------------                             3.6/11.6 MB 15.2 MB/s eta 0:00:01
     ------------                             3.6/11.6 MB 15.2 MB/s eta 0:00:01
     ------------                             3.6/11.6 MB 15.2 MB/s eta 0:00:01
     ------------                             3.6/11.6 MB 15.2 MB/s eta 0:00:01
     ------------                             3.6/11.6 MB 15.2 MB/s eta 0:00:01
     ------------                             3.6/11.6 MB 15.2 MB/s eta 0:00:01
     ------------                             3.6/11.6 MB 15.2 MB/s eta 0:00:01
     ------------                             3.6/11.6 MB 15.2 MB/s eta 0:00:01
     ------------                             3.7/11.6 MB 4.2 MB/s eta 0:00:02
     --------------                           4.3/11.6 MB 4.7 MB/s eta 0:00:02
     -----------------                        5.2/11.6 MB 5.3 MB/s eta 0:00:02
     -------------------                      5.8/11.6 MB 5.7 MB/s eta 0:00:02
     ---------------------                    6.4/11.6 MB 5.9 MB/s eta 0:00:01
     ----------------------                   6.6/11.6 MB 6.1 MB/s eta 0:00:01
     ----------------------                   6.6/11.6 MB 6.1 MB/s eta 0:00:01
     ----------------------                   6.6/11.6 MB 6.1 MB/s eta 0:00:01
     ----------------------                   6.6/11.6 MB 6.1 MB/s eta 0:00:01
     ----------------------                   6.6/11.6 MB 6.1 MB/s eta 0:00:01
     ----------------------                   6.6/11.6 MB 6.1 MB/s eta 0:00:01
     ----------------------                   6.6/11.6 MB 6.1 MB/s eta 0:00:01
     ----------------------                   6.6/11.6 MB 6.1 MB/s eta 0:00:01
     ----------------------                   6.6/11.6 MB 6.1 MB/s eta 0:00:01
     ----------------------                   6.6/11.6 MB 6.1 MB/s eta 0:00:01
     ----------------------                   6.6/11.6 MB 6.1 MB/s eta 0:00:01
     ----------------------                   6.6/11.6 MB 6.1 MB/s eta 0:00:01
     ----------------------                   6.6/11.6 MB 6.1 MB/s eta 0:00:01
     ----------------------                   6.6/11.6 MB 6.1 MB/s eta 0:00:01
     ------------------------                 7.1/11.6 MB 4.0 MB/s eta 0:00:02
     ---------------------------              7.8/11.6 MB 4.3 MB/s eta 0:00:01
     ------------------------------           8.7/11.6 MB 4.7 MB/s eta 0:00:01
     ---------------------------------        9.7/11.6 MB 5.1 MB/s eta 0:00:01
     ---------------------------------        9.7/11.6 MB 5.1 MB/s eta 0:00:01
     ---------------------------------        9.7/11.6 MB 5.1 MB/s eta 0:00:01
     ---------------------------------        9.7/11.6 MB 5.1 MB/s eta 0:00:01
     ---------------------------------        9.7/11.6 MB 5.1 MB/s eta 0:00:01
     ---------------------------------        9.7/11.6 MB 5.1 MB/s eta 0:00:01
     ---------------------------------        9.7/11.6 MB 5.1 MB/s eta 0:00:01
     ---------------------------------        9.7/11.6 MB 5.1 MB/s eta 0:00:01
     ---------------------------------        9.7/11.6 MB 5.1 MB/s eta 0:00:01
     ---------------------------------        9.7/11.6 MB 5.1 MB/s eta 0:00:01
     ---------------------------------        9.7/11.6 MB 5.1 MB/s eta 0:00:01
     ---------------------------------        9.7/11.6 MB 5.1 MB/s eta 0:00:01
     ---------------------------------        9.7/11.6 MB 5.1 MB/s eta 0:00:01
     ---------------------------------        9.7/11.6 MB 5.1 MB/s eta 0:00:01
     -----------------------------------      10.2/11.6 MB 4.0 MB/s eta 0:00:01
     ------------------------------------     10.7/11.6 MB 4.0 MB/s eta 0:00:01
     ---------------------------------------  11.4/11.6 MB 4.0 MB/s eta 0:00:01
     ---------------------------------------  11.6/11.6 MB 4.0 MB/s eta 0:00:01
     ---------------------------------------- 11.6/11.6 MB 3.9 MB/s eta 0:00:00
Collecting numpy<2,>=1.23.2 (from pandas)
  Downloading numpy-1.26.4-cp311-cp311-win_amd64.whl (15.8 MB)
                                              0.0/15.8 MB ? eta -:--:--
     -                                        0.6/15.8 MB 18.9 MB/s eta 0:00:01
     ---                                      1.2/15.8 MB 15.8 MB/s eta 0:00:01
     ----                                     1.8/15.8 MB 14.7 MB/s eta 0:00:01
     ------                                   2.5/15.8 MB 13.2 MB/s eta 0:00:02
     -------                                  3.1/15.8 MB 13.9 MB/s eta 0:00:01
     -------                                  3.1/15.8 MB 13.9 MB/s eta 0:00:01
     -------                                  3.1/15.8 MB 13.9 MB/s eta 0:00:01
     -------                                  3.1/15.8 MB 13.9 MB/s eta 0:00:01
     -------                                  3.1/15.8 MB 13.9 MB/s eta 0:00:01
     -------                                  3.1/15.8 MB 13.9 MB/s eta 0:00:01
     -------                                  3.1/15.8 MB 13.9 MB/s eta 0:00:01
     -------                                  3.1/15.8 MB 13.9 MB/s eta 0:00:01
     -------                                  3.1/15.8 MB 13.9 MB/s eta 0:00:01
     -------                                  3.1/15.8 MB 13.9 MB/s eta 0:00:01
     -------                                  3.1/15.8 MB 13.9 MB/s eta 0:00:01
     -------                                  3.1/15.8 MB 13.9 MB/s eta 0:00:01
     -------                                  3.1/15.8 MB 13.9 MB/s eta 0:00:01
     -------                                  3.1/15.8 MB 13.9 MB/s eta 0:00:01
     --------                                 3.4/15.8 MB 3.9 MB/s eta 0:00:04
     ----------                               4.0/15.8 MB 4.4 MB/s eta 0:00:03
     -----------                              4.7/15.8 MB 4.9 MB/s eta 0:00:03
     -------------                            5.4/15.8 MB 5.3 MB/s eta 0:00:02
     --------------                           5.9/15.8 MB 5.5 MB/s eta 0:00:02
     ---------------                          6.1/15.8 MB 5.7 MB/s eta 0:00:02
     ---------------                          6.1/15.8 MB 5.7 MB/s eta 0:00:02
     ---------------                          6.1/15.8 MB 5.7 MB/s eta 0:00:02
     ---------------                          6.1/15.8 MB 5.7 MB/s eta 0:00:02
     ---------------                          6.1/15.8 MB 5.7 MB/s eta 0:00:02
     ---------------                          6.1/15.8 MB 5.7 MB/s eta 0:00:02
     ---------------                          6.1/15.8 MB 5.7 MB/s eta 0:00:02
     ---------------                          6.1/15.8 MB 5.7 MB/s eta 0:00:02
     ---------------                          6.1/15.8 MB 5.7 MB/s eta 0:00:02
     ---------------                          6.1/15.8 MB 5.7 MB/s eta 0:00:02
     ---------------                          6.1/15.8 MB 5.7 MB/s eta 0:00:02
     ---------------                          6.1/15.8 MB 5.7 MB/s eta 0:00:02
     ---------------                          6.1/15.8 MB 5.7 MB/s eta 0:00:02
     ---------------                          6.1/15.8 MB 3.6 MB/s eta 0:00:03
     -----------------                        6.8/15.8 MB 3.8 MB/s eta 0:00:03
     --------------------                     8.2/15.8 MB 4.5 MB/s eta 0:00:02
     -----------------------                  9.2/15.8 MB 5.0 MB/s eta 0:00:02
     -----------------------                  9.2/15.8 MB 5.0 MB/s eta 0:00:02
     -----------------------                  9.2/15.8 MB 5.0 MB/s eta 0:00:02
     -----------------------                  9.2/15.8 MB 5.0 MB/s eta 0:00:02
     -----------------------                  9.2/15.8 MB 5.0 MB/s eta 0:00:02
     -----------------------                  9.2/15.8 MB 5.0 MB/s eta 0:00:02
     -----------------------                  9.2/15.8 MB 5.0 MB/s eta 0:00:02
     -----------------------                  9.2/15.8 MB 5.0 MB/s eta 0:00:02
     -----------------------                  9.2/15.8 MB 5.0 MB/s eta 0:00:02
     -----------------------                  9.2/15.8 MB 5.0 MB/s eta 0:00:02
     -----------------------                  9.2/15.8 MB 5.0 MB/s eta 0:00:02
     -----------------------                  9.2/15.8 MB 5.0 MB/s eta 0:00:02
     -----------------------                  9.2/15.8 MB 5.0 MB/s eta 0:00:02
     -----------------------                  9.3/15.8 MB 3.7 MB/s eta 0:00:02
     -------------------------                10.1/15.8 MB 4.0 MB/s eta 0:00:02
     ---------------------------              10.9/15.8 MB 4.0 MB/s eta 0:00:02
     -----------------------------            11.7/15.8 MB 4.1 MB/s eta 0:00:01
     -------------------------------          12.3/15.8 MB 4.1 MB/s eta 0:00:01
     -------------------------------          12.3/15.8 MB 4.1 MB/s eta 0:00:01
     -------------------------------          12.3/15.8 MB 4.1 MB/s eta 0:00:01
     -------------------------------          12.3/15.8 MB 4.1 MB/s eta 0:00:01
     -------------------------------          12.3/15.8 MB 4.1 MB/s eta 0:00:01
     -------------------------------          12.3/15.8 MB 4.1 MB/s eta 0:00:01
     -------------------------------          12.3/15.8 MB 4.1 MB/s eta 0:00:01
     -------------------------------          12.3/15.8 MB 4.1 MB/s eta 0:00:01
     -------------------------------          12.3/15.8 MB 4.1 MB/s eta 0:00:01
     -------------------------------          12.3/15.8 MB 4.1 MB/s eta 0:00:01
     -------------------------------          12.3/15.8 MB 4.1 MB/s eta 0:00:01
     -------------------------------          12.3/15.8 MB 4.1 MB/s eta 0:00:01
     -------------------------------          12.3/15.8 MB 4.1 MB/s eta 0:00:01
     -------------------------------          12.3/15.8 MB 3.2 MB/s eta 0:00:02
     -------------------------------          12.6/15.8 MB 3.2 MB/s eta 0:00:01
     --------------------------------         13.0/15.8 MB 3.2 MB/s eta 0:00:01
     ---------------------------------        13.3/15.8 MB 4.0 MB/s eta 0:00:01
     ----------------------------------       13.6/15.8 MB 3.9 MB/s eta 0:00:01
     ----------------------------------       13.8/15.8 MB 3.9 MB/s eta 0:00:01
     -----------------------------------      13.9/15.8 MB 3.9 MB/s eta 0:00:01
     -----------------------------------      13.9/15.8 MB 3.9 MB/s eta 0:00:01
     -----------------------------------      13.9/15.8 MB 3.9 MB/s eta 0:00:01
     -----------------------------------      13.9/15.8 MB 3.9 MB/s eta 0:00:01
     -----------------------------------      13.9/15.8 MB 3.9 MB/s eta 0:00:01
     -----------------------------------      13.9/15.8 MB 3.9 MB/s eta 0:00:01
     -----------------------------------      14.0/15.8 MB 3.5 MB/s eta 0:00:01
     -----------------------------------      14.2/15.8 MB 3.4 MB/s eta 0:00:01
     ------------------------------------     14.5/15.8 MB 3.4 MB/s eta 0:00:01
     -------------------------------------    14.8/15.8 MB 3.4 MB/s eta 0:00:01
     -------------------------------------    15.0/15.8 MB 3.3 MB/s eta 0:00:01
     --------------------------------------   15.2/15.8 MB 3.3 MB/s eta 0:00:01
     ---------------------------------------  15.6/15.8 MB 3.3 MB/s eta 0:00:01
     ---------------------------------------  15.8/15.8 MB 3.3 MB/s eta 0:00:01
     ---------------------------------------  15.8/15.8 MB 3.3 MB/s eta 0:00:01
     ---------------------------------------- 15.8/15.8 MB 3.1 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.8.2 in c:\python311\lib\site-packages (from pandas) (2.8.2)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2024.1-py2.py3-none-any.whl (505 kB)
                                              0.0/505.5 kB ? eta -:--:--
     ------------------------------------  501.8/505.5 kB 10.5 MB/s eta 0:00:01
     ------------------------------------- 505.5/505.5 kB 10.5 MB/s eta 0:00:00
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2024.1-py2.py3-none-any.whl (345 kB)
                                              0.0/345.4 kB ? eta -:--:--
     ------------------------------------- 345.4/345.4 kB 22.3 MB/s eta 0:00:00
Requirement already satisfied: six>=1.5 in c:\python311\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Installing collected packages: pytz, tzdata, numpy, pandas
Successfully installed numpy-1.26.4 pandas-2.2.1 pytz-2024.1 tzdata-2024.1
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.1.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [13]:
import pandas as pd 
mark = pd.read_csv(r"Dados3 Marketing.csv", sep=';')
print(mark.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             41188 non-null  int64
 1   job             41188 non-null  object
 2   marital         41188 non-null  object
 3   education       41188 non-null  object
 4   default         41188 non-null  object
 5   housing         41188 non-null  object
 6   loan            41188 non-null  object
 7   contact         41188 non-null  object
 8   month           41188 non-null  object
 9   day_of_week     41188 non-null  object
 10  duration        41188 non-null  int64
 11  campaign        41188 non-null  int64
 12  pdays           41188 non-null  int64
 13  previous        41188 non-null  int64
 14  poutcome        41188 non-null  object
 15  emp.var.rate    41188 non-null  float64
 16  cons.price.idx  41188 non-null  float64
 17  cons.conf.idx   41188 non-null  float64
 18  euribor3m       41188 non-null  float64
 19  nr.employed     41188 non-null  float64
 20  y               41188 non-null  object
dtypes: float64(5), int64(5), object(11)
memory usage: 6.6+ MB
None

In [14]:
import pandas as pd 
fraudes= pd.read_csv(r"Dados1 Cartoes.csv", sep=';')
print(fraudes.info)

<bound method DataFrame.info of        distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
0       57.87785658389723,0.3111400080477545,1.9459399...
1       10.829942699255545,0.17559150228166587,1.29421...
2       5.091079490616996,0.8051525945853258,0.4277145...
3       2.2475643282963613,5.60004354707232,0.36266257...
4       44.19093600261837,0.5664862680583477,2.2227672...
...                                                   ...
999995  2.2071007085956595,0.11265130279473716,1.62679...
999996  19.872725762075127,2.6839037264517254,2.778302...
999997  2.914856986796768,1.4726866870566833,0.2180754...
999998  4.258729391720518,0.24202336594551443,0.475822...
999999  58.10812496080576,0.3181101207150046,0.3869198...

[1000000 rows x 1 columns]>

In [ ]:
fraudes_dist = fraudes.sort_values('distance_from_home')

In [ ]:
print(fraudes.tail())
print("-------------------------------------------------------")
print(fraudes_dist.tail())

In [ ]:
print(mark.tail())
print("-------------------------------------------------------")
print("-------------------------------------------------------")
print("-------------------------------------------------------")
print(mark)

In [17]:
mark_age = mark.sort_values('age')

In [18]:
print(mark_age.head(10))
print(mark_age.tail(10))

       age      job marital    education default  housing     loan    contact  \
38274   17  student  single      unknown      no       no      yes   cellular
37579   17  student  single     basic.9y      no  unknown  unknown   cellular
37539   17  student  single     basic.9y      no      yes       no   cellular
37140   17  student  single      unknown      no      yes       no   cellular
37558   17  student  single     basic.9y      no      yes       no   cellular
38832   18  student  single  high.school      no       no       no   cellular
24110   18  student  single  high.school      no       no       no  telephone
37626   18  student  single     basic.6y      no      yes       no   cellular
27792   18  student  single  high.school      no      yes      yes   cellular
37955   18  student  single      unknown      no      yes       no   cellular

      month day_of_week  ...  campaign  pdays  previous     poutcome  \
38274   oct         tue  ...         1      2         2      success
37579   aug         fri  ...         2    999         1      failure
37539   aug         fri  ...         2    999         2      failure
37140   aug         wed  ...         3      4         2      success
37558   aug         fri  ...         3      4         2      success
38832   nov         fri  ...         2      7         2      failure
24110   nov         thu  ...         1    999         0  nonexistent
37626   aug         mon  ...         1    999         0  nonexistent
27792   mar         tue  ...         1    999         0  nonexistent
37955   sep         fri  ...         1    999         0  nonexistent

      emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  nr.employed    y
38274         -3.4          92.431          -26.9      0.742       5017.5  yes
37579         -2.9          92.201          -31.4      0.869       5076.2  yes
37539         -2.9          92.201          -31.4      0.869       5076.2   no
37140         -2.9          92.201          -31.4      0.884       5076.2   no
37558         -2.9          92.201          -31.4      0.869       5076.2   no
38832         -3.4          92.649          -30.1      0.714       5017.5  yes
24110         -0.1          93.200          -42.0      4.245       5195.8   no
37626         -2.9          92.201          -31.4      0.861       5076.2   no
27792         -1.8          92.843          -50.0      1.687       5099.1   no
37955         -3.4          92.379          -29.8      0.803       5017.5  yes

[10 rows x 21 columns]
       age      job   marital          education  default housing loan  \
38022   91  retired   married  university.degree       no     yes  yes
38032   91  retired   married  university.degree       no      no  yes
39734   92  retired  divorced            unknown  unknown      no   no
39655   92  retired   married            unknown       no     yes   no
40469   92  retired   married            unknown       no      no  yes
40450   92  retired   married            unknown       no      no  yes
38921   94  retired   married           basic.9y       no      no   no
27826   95  retired  divorced           basic.6y       no      no   no
38455   98  retired   married           basic.4y  unknown     yes   no
38452   98  retired   married           basic.4y  unknown     yes   no

        contact month day_of_week  ...  campaign  pdays  previous  \
38022  cellular   sep         wed  ...         1    999         2
38032  cellular   sep         wed  ...         2    999         0
39734  cellular   may         wed  ...         3    999         1
39655  cellular   may         thu  ...         1      6         2
40469  cellular   aug         wed  ...         1      3         4
40450  cellular   aug         tue  ...         1      3         1
38921  cellular   nov         wed  ...         1    999         1
27826  cellular   mar         thu  ...         1    999         0
38455  cellular   oct         fri  ...         2    999         0
38452  cellular   oct         fri  ...         1      2         2

          poutcome emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  \
38022      failure         -3.4          92.379          -29.8      0.781
38032  nonexistent         -3.4          92.379          -29.8      0.781
39734      failure         -1.8          93.876          -40.0      0.697
39655      success         -1.8          93.876          -40.0      0.683
40469      success         -1.7          94.027          -38.3      0.903
40450      success         -1.7          94.027          -38.3      0.904
38921      failure         -3.4          92.649          -30.1      0.716
27826  nonexistent         -1.8          92.843          -50.0      1.650
38455  nonexistent         -3.4          92.431          -26.9      0.730
38452      success         -3.4          92.431          -26.9      0.730

       nr.employed    y
38022       5017.5   no
38032       5017.5   no
39734       5008.7  yes
39655       5008.7   no
40469       4991.6  yes
40450       4991.6  yes
38921       5017.5   no
27826       5099.1   no
38455       5017.5  yes
38452       5017.5  yes

[10 rows x 21 columns]

In [24]:
mark_age_edu = mark.sort_values(['age', 'education'])

In [25]:
print(mark_age_edu.head(10))
print(mark_age_edu.tail(10))

       age      job marital education default  housing     loan    contact  \
37539   17  student  single  basic.9y      no      yes       no   cellular
37558   17  student  single  basic.9y      no      yes       no   cellular
37579   17  student  single  basic.9y      no  unknown  unknown   cellular
37140   17  student  single   unknown      no      yes       no   cellular
38274   17  student  single   unknown      no       no      yes   cellular
30142   18  student  single  basic.4y      no       no       no   cellular
30349   18  student  single  basic.4y      no      yes      yes   cellular
39903   18  student  single  basic.4y      no      yes       no   cellular
41088   18  student  single  basic.4y      no      yes       no  telephone
37626   18  student  single  basic.6y      no      yes       no   cellular

      month day_of_week  ...  campaign  pdays  previous     poutcome  \
37539   aug         fri  ...         2    999         2      failure
37558   aug         fri  ...         3      4         2      success
37579   aug         fri  ...         2    999         1      failure
37140   aug         wed  ...         3      4         2      success
38274   oct         tue  ...         1      2         2      success
30142   apr         thu  ...         1    999         0  nonexistent
30349   apr         thu  ...         2    999         0  nonexistent
39903   jun         tue  ...         1    999         0  nonexistent
41088   nov         tue  ...         1     13         2      success
37626   aug         mon  ...         1    999         0  nonexistent

      emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  nr.employed    y
37539         -2.9          92.201          -31.4      0.869       5076.2   no
37558         -2.9          92.201          -31.4      0.869       5076.2   no
37579         -2.9          92.201          -31.4      0.869       5076.2  yes
37140         -2.9          92.201          -31.4      0.884       5076.2   no
38274         -3.4          92.431          -26.9      0.742       5017.5  yes
30142         -1.8          93.075          -47.1      1.365       5099.1   no
30349         -1.8          93.075          -47.1      1.365       5099.1   no
39903         -1.7          94.055          -39.8      0.737       4991.6   no
41088         -1.1          94.767          -50.8      1.049       4963.6  yes
37626         -2.9          92.201          -31.4      0.861       5076.2   no

[10 rows x 21 columns]
       age      job   marital          education  default housing loan  \
38022   91  retired   married  university.degree       no     yes  yes
38032   91  retired   married  university.degree       no      no  yes
39655   92  retired   married            unknown       no     yes   no
39734   92  retired  divorced            unknown  unknown      no   no
40450   92  retired   married            unknown       no      no  yes
40469   92  retired   married            unknown       no      no  yes
38921   94  retired   married           basic.9y       no      no   no
27826   95  retired  divorced           basic.6y       no      no   no
38452   98  retired   married           basic.4y  unknown     yes   no
38455   98  retired   married           basic.4y  unknown     yes   no

        contact month day_of_week  ...  campaign  pdays  previous  \
38022  cellular   sep         wed  ...         1    999         2
38032  cellular   sep         wed  ...         2    999         0
39655  cellular   may         thu  ...         1      6         2
39734  cellular   may         wed  ...         3    999         1
40450  cellular   aug         tue  ...         1      3         1
40469  cellular   aug         wed  ...         1      3         4
38921  cellular   nov         wed  ...         1    999         1
27826  cellular   mar         thu  ...         1    999         0
38452  cellular   oct         fri  ...         1      2         2
38455  cellular   oct         fri  ...         2    999         0

          poutcome emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  \
38022      failure         -3.4          92.379          -29.8      0.781
38032  nonexistent         -3.4          92.379          -29.8      0.781
39655      success         -1.8          93.876          -40.0      0.683
39734      failure         -1.8          93.876          -40.0      0.697
40450      success         -1.7          94.027          -38.3      0.904
40469      success         -1.7          94.027          -38.3      0.903
38921      failure         -3.4          92.649          -30.1      0.716
27826  nonexistent         -1.8          92.843          -50.0      1.650
38452      success         -3.4          92.431          -26.9      0.730
38455  nonexistent         -3.4          92.431          -26.9      0.730

       nr.employed    y
38022       5017.5   no
38032       5017.5   no
39655       5008.7   no
39734       5008.7  yes
40450       4991.6  yes
40469       4991.6  yes
38921       5017.5   no
27826       5099.1   no
38452       5017.5  yes
38455       5017.5  yes

[10 rows x 21 columns]

In [22]:
mark_age = mark.sort_values('age', ascending=False)

In [26]:
print(mark_age.head(10))
print(mark_age.tail(10))

       age      job   marital          education  default housing loan  \
38452   98  retired   married           basic.4y  unknown     yes   no
38455   98  retired   married           basic.4y  unknown     yes   no
27826   95  retired  divorced           basic.6y       no      no   no
38921   94  retired   married           basic.9y       no      no   no
39655   92  retired   married            unknown       no     yes   no
40450   92  retired   married            unknown       no      no  yes
39734   92  retired  divorced            unknown  unknown      no   no
40469   92  retired   married            unknown       no      no  yes
38032   91  retired   married  university.degree       no      no  yes
38022   91  retired   married  university.degree       no     yes  yes

        contact month day_of_week  ...  campaign  pdays  previous  \
38452  cellular   oct         fri  ...         1      2         2
38455  cellular   oct         fri  ...         2    999         0
27826  cellular   mar         thu  ...         1    999         0
38921  cellular   nov         wed  ...         1    999         1
39655  cellular   may         thu  ...         1      6         2
40450  cellular   aug         tue  ...         1      3         1
39734  cellular   may         wed  ...         3    999         1
40469  cellular   aug         wed  ...         1      3         4
38032  cellular   sep         wed  ...         2    999         0
38022  cellular   sep         wed  ...         1    999         2

          poutcome emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  \
38452      success         -3.4          92.431          -26.9      0.730
38455  nonexistent         -3.4          92.431          -26.9      0.730
27826  nonexistent         -1.8          92.843          -50.0      1.650
38921      failure         -3.4          92.649          -30.1      0.716
39655      success         -1.8          93.876          -40.0      0.683
40450      success         -1.7          94.027          -38.3      0.904
39734      failure         -1.8          93.876          -40.0      0.697
40469      success         -1.7          94.027          -38.3      0.903
38032  nonexistent         -3.4          92.379          -29.8      0.781
38022      failure         -3.4          92.379          -29.8      0.781

       nr.employed    y
38452       5017.5  yes
38455       5017.5  yes
27826       5099.1   no
38921       5017.5   no
39655       5008.7   no
40450       4991.6  yes
39734       5008.7  yes
40469       4991.6  yes
38032       5017.5   no
38022       5017.5   no

[10 rows x 21 columns]
       age      job marital    education default  housing     loan    contact  \
39057   18  student  single     basic.9y      no       no       no   cellular
24110   18  student  single  high.school      no       no       no  telephone
35871   18  student  single  high.school      no       no       no   cellular
35872   18  student  single  high.school      no      yes       no   cellular
39903   18  student  single     basic.4y      no      yes       no   cellular
37579   17  student  single     basic.9y      no  unknown  unknown   cellular
37539   17  student  single     basic.9y      no      yes       no   cellular
38274   17  student  single      unknown      no       no      yes   cellular
37140   17  student  single      unknown      no      yes       no   cellular
37558   17  student  single     basic.9y      no      yes       no   cellular

      month day_of_week  ...  campaign  pdays  previous     poutcome  \
39057   dec         thu  ...         2    999         0  nonexistent
24110   nov         thu  ...         1    999         0  nonexistent
35871   may         fri  ...         1    999         1      failure
35872   may         fri  ...         1      1         2      success
39903   jun         tue  ...         1    999         0  nonexistent
37579   aug         fri  ...         2    999         1      failure
37539   aug         fri  ...         2    999         2      failure
38274   oct         tue  ...         1      2         2      success
37140   aug         wed  ...         3      4         2      success
37558   aug         fri  ...         3      4         2      success

      emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  nr.employed    y
39057         -3.0          92.713          -33.0      0.712       5023.5  yes
24110         -0.1          93.200          -42.0      4.245       5195.8   no
35871         -1.8          92.893          -46.2      1.259       5099.1  yes
35872         -1.8          92.893          -46.2      1.259       5099.1   no
39903         -1.7          94.055          -39.8      0.737       4991.6   no
37579         -2.9          92.201          -31.4      0.869       5076.2  yes
37539         -2.9          92.201          -31.4      0.869       5076.2   no
38274         -3.4          92.431          -26.9      0.742       5017.5  yes
37140         -2.9          92.201          -31.4      0.884       5076.2   no
37558         -2.9          92.201          -31.4      0.869       5076.2   no

[10 rows x 21 columns]

In [ ]:
mark.sort_index(['age', 'education', 'marital'], ascending=False, inplace=True)

In [27]:
print(mark.head())

   age        job  marital    education  default housing loan    contact  \
0   56  housemaid  married     basic.4y       no      no   no  telephone
1   57   services  married  high.school  unknown      no   no  telephone
2   37   services  married  high.school       no     yes   no  telephone
3   40     admin.  married     basic.6y       no      no   no  telephone
4   56   services  married  high.school       no      no  yes  telephone

  month day_of_week  ...  campaign  pdays  previous     poutcome emp.var.rate  \
0   may         mon  ...         1    999         0  nonexistent          1.1
1   may         mon  ...         1    999         0  nonexistent          1.1
2   may         mon  ...         1    999         0  nonexistent          1.1
3   may         mon  ...         1    999         0  nonexistent          1.1
4   may         mon  ...         1    999         0  nonexistent          1.1

   cons.price.idx  cons.conf.idx  euribor3m  nr.employed   y
0          93.994          -36.4      4.857       5191.0  no
1          93.994          -36.4      4.857       5191.0  no
2          93.994          -36.4      4.857       5191.0  no
3          93.994          -36.4      4.857       5191.0  no
4          93.994          -36.4      4.857       5191.0  no

[5 rows x 21 columns]

In [29]:
mark_married = mark[mark['marital'] == 'marreid']
print(mark_married)

Empty DataFrame
Columns: [age, job, marital, education, default, housing, loan, contact, month, day_of_week, duration, campaign, pdays, previous, poutcome, emp.var.rate, cons.price.idx, cons.conf.idx, euribor3m, nr.employed, y]
Index: []

[0 rows x 21 columns]

In [30]:
mark_unemp = mark[mark['job'] == 'unemployed']
print(mark_unemp)

       age         job  marital            education  default housing loan  \
20      30  unemployed  married          high.school       no      no   no
58      55  unemployed  married  professional.course  unknown     yes  yes
93      33  unemployed  married             basic.9y       no      no   no
111     58  unemployed  married             basic.4y  unknown      no   no
140     43  unemployed   single    university.degree       no     yes   no
...    ...         ...      ...                  ...      ...     ...  ...
41032   36  unemployed  married          high.school       no     yes   no
41132   41  unemployed  married             basic.9y       no      no   no
41136   54  unemployed  married  professional.course       no     yes   no
41138   58  unemployed  married    university.degree       no     yes   no
41182   29  unemployed   single             basic.4y       no     yes   no

         contact month day_of_week  ...  campaign  pdays  previous  \
20     telephone   may         mon  ...         1    999         0
58     telephone   may         mon  ...         1    999         0
93     telephone   may         mon  ...         1    999         0
111    telephone   may         mon  ...         2    999         0
140    telephone   may         mon  ...         1    999         0
...          ...   ...         ...  ...       ...    ...       ...
41032   cellular   oct         mon  ...         1      3         1
41132   cellular   nov         thu  ...         2      3         2
41136  telephone   nov         thu  ...         2     10         4
41138   cellular   nov         thu  ...         2    999         0
41182   cellular   nov         fri  ...         1      9         1

          poutcome emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  \
20     nonexistent          1.1          93.994          -36.4      4.857
58     nonexistent          1.1          93.994          -36.4      4.857
93     nonexistent          1.1          93.994          -36.4      4.857
111    nonexistent          1.1          93.994          -36.4      4.857
140    nonexistent          1.1          93.994          -36.4      4.857
...            ...          ...             ...            ...        ...
41032      success         -1.1          94.601          -49.5      1.032
41132      success         -1.1          94.767          -50.8      1.041
41136      failure         -1.1          94.767          -50.8      1.041
41138  nonexistent         -1.1          94.767          -50.8      1.041
41182      success         -1.1          94.767          -50.8      1.028

       nr.employed    y
20          5191.0   no
58          5191.0   no
93          5191.0   no
111         5191.0   no
140         5191.0   no
...            ...  ...
41032       4963.6  yes
41132       4963.6  yes
41136       4963.6   no
41138       4963.6  yes
41182       4963.6   no

[1014 rows x 21 columns]

In [31]:
mark_50 = mark[mark['age'] > 49]
print(mark_50)

       age        job   marital            education  default housing loan  \
0       56  housemaid   married             basic.4y       no      no   no
1       57   services   married          high.school  unknown      no   no
4       56   services   married          high.school       no      no  yes
6       59     admin.   married  professional.course       no      no   no
13      57  housemaid  divorced             basic.4y       no     yes   no
...    ...        ...       ...                  ...      ...     ...  ...
41178   62    retired   married    university.degree       no      no   no
41179   64    retired  divorced  professional.course       no     yes   no
41183   73    retired   married  professional.course       no     yes   no
41185   56    retired   married    university.degree       no     yes   no
41187   74    retired   married  professional.course       no     yes   no

         contact month day_of_week  ...  campaign  pdays  previous  \
0      telephone   may         mon  ...         1    999         0
1      telephone   may         mon  ...         1    999         0
4      telephone   may         mon  ...         1    999         0
6      telephone   may         mon  ...         1    999         0
13     telephone   may         mon  ...         1    999         0
...          ...   ...         ...  ...       ...    ...       ...
41178   cellular   nov         thu  ...         2      6         3
41179   cellular   nov         fri  ...         3    999         0
41183   cellular   nov         fri  ...         1    999         0
41185   cellular   nov         fri  ...         2    999         0
41187   cellular   nov         fri  ...         3    999         1

          poutcome emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  \
0      nonexistent          1.1          93.994          -36.4      4.857
1      nonexistent          1.1          93.994          -36.4      4.857
4      nonexistent          1.1          93.994          -36.4      4.857
6      nonexistent          1.1          93.994          -36.4      4.857
13     nonexistent          1.1          93.994          -36.4      4.857
...            ...          ...             ...            ...        ...
41178      success         -1.1          94.767          -50.8      1.031
41179  nonexistent         -1.1          94.767          -50.8      1.028
41183  nonexistent         -1.1          94.767          -50.8      1.028
41185  nonexistent         -1.1          94.767          -50.8      1.028
41187      failure         -1.1          94.767          -50.8      1.028

       nr.employed    y
0           5191.0   no
1           5191.0   no
4           5191.0   no
6           5191.0   no
13          5191.0   no
...            ...  ...
41178       4963.6  yes
41179       4963.6   no
41183       4963.6  yes
41185       4963.6   no
41187       4963.6   no

[8055 rows x 21 columns]